### ISSUE TITLE
github部署问题

### ISSUE THREAD

**Issue by orangegk** [wforguo/vue3-quick-start#1]
您好！请问如何像您这个项目一样，在github上部署前端项目，同时保证前端项目是history路由模式呢，

**Comment by web-farmer** [comment]
> 您好！请问如何像您这个项目一样，在github上部署前端项目，同时保证前端项目是history路由模式呢，

部署是正常的，用的 GitHub Pages，
只不过不支持 history路由模式，这个项目也是不行的，刷新之后路由丢失，你可以试试看

**Comment by orangegk** [comment]
我现在想在github pages上部署一个前端项目，为了好看避免出现#号，想用history路由模式，但是就是会出现刷新之后页面404，请问您有什么解决方案推荐吗?

**Comment by web-farmer** [comment]
> 我现在想在github pages上部署一个前端项目，为了好看避免出现#号，想用history路由模式，但是就是会出现刷新之后页面404，请问您有什么解决方案推荐吗?

我看到有人是把404页面做了修改，应该是重新去调到一个存在的页面

[https://blog.csdn.net/qq_21567385/article/details/107884942](https://blog.csdn.net/qq_21567385/article/details/107884942)

但我没有尝试过，我一般其他项目都在自己服务器 用docker部署

**Comment by orangegk** [comment]
我之前试过把index.html的内容复制到404.html,但是感觉效果没有后端配置重定向的效果好，
好的，感谢您的建议。
